---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: dev
spec:
  interval: 30m
  url: https://charts.bitnami.com/bitnami

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: homol
spec:
  interval: 30m
  url: https://charts.bitnami.com/bitnami

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: prod
spec:
  interval: 30m
  url: https://charts.bitnami.com/bitnami
