apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app
  namespace: dev
spec:
  interval: 5m
  releaseName: app-release
  chart:
    spec:
      chart: nginx
      # version: 5.0.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 10m
  values:
    replicaCount: 2
