---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: sample-chart
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://helm.github.io/examples
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app
  namespace: dev
spec:
  interval: 5m
  releaseName: app-release
  chart:
    spec:
      chart: nginx
      # version: 5.0.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 10m
  values:
    replicaCount: 2
