# Sample Source
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: sample-chart
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://helm.github.io/examples

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello-world
  namespace: dev
spec:
  interval: 5m
  releaseName: hello-world
  chart:
    spec:
      chart: hello-world
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: hello-world
        namespace: dev
      interval: 10m
  values:
    replicaCount: 1
