---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginx-app-helm
  namespace: dev
spec:
  interval: 10m
  url:  ecr://073346639909.dkr.ecr.us-east-1.amazonaws.com/nginx-helm-app
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  labels:
    app: nginx-app-helm
  name: nginx-app-helm
  namespace: dev
spec:
  chart: nginx-app-helm
    spec:
      chart: nginx-app-helm
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: nginx-app-helm
        namespace: dev
      interval: 10m
  values:
    replicaCount: 2
