---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    app: nginx-app
  name: nginx-app
  namespace: dev
spec:
  chart:
    name: nginx-app-helm
    repository: ecr://073346639909.dkr.ecr.region.amazonaws.com/nginx-app-helm
    version: 0.1.0
