---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    app: nginx-app
  name: nginx-app
  namespace: dev
spec:
  chart:
    name: app
    repository: ecr://073346639909.dkr.ecr.us-east-1.amazonaws.com/nginx-app:0.1.0
    version: 0.1.0
