---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo
  namespace: dev
spec:
  interval: 10m
  url: ecr://073346639909.dkr.ecr.us-east-1.amazonaws.com/nginx-app-helm:0.1.0
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-app
  namespace: dev
spec:
  interval: 5m
  releaseName: nginx-app-helm
  chart:
    spec:
      chart: nginx-app-helm
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: nginx-app
        namespace: dev
      interval: 10m
  values:
    replicaCount: 3
